### ISSUE TITLE
when i use hale+ffmpeg，there is a problem with the sound

### ISSUE THREAD

**Issue by hgx123** [ripieces/advancedfx#708]
i have record one demo two times，but the two sounds are different

here is the video file url
https://pan.baidu.com/s/1DTEDxcLJwhNXVa1RdeOrBg  提取码: a66q

**Comment by dtugend** [comment]
I don't have a baidu account / access, so I can not check the files.
In case there is only a slight difference: CS:GO is not fully deterministic, so the sounds will not be 100% the same usually.
That's why HLAE supports recording multiple streams at once with mirv_streams, otherwise the footage would not match up 100%.

**Comment by hgx123** [comment]
> I don't have a baidu account / access, so I can not check the files.
> In case there is only a slight difference: CS:GO is not fully deterministic, so the sounds will not be 100% the same usually.
> That's why HLAE supports recording multiple streams at once with mirv_streams, otherwise the footage would not match up 100%.

ok，i will try more
