### ISSUE TITLE
AGR for GoldSrcs import blender gets framerate mismatch?

### ISSUE THREAD

**Issue by 591280714** [ripieces/advancedfx#712]
![JQGA4LSWM5N$I350{(~)W T](https://user-images.githubusercontent.com/45847377/134653460-c2acc3d9-0afd-48bf-a55c-a58793f2dff1.png)
All the time!!
![JH9VUUZHDEABCE~Z`K2CQXO](https://user-images.githubusercontent.com/45847377/134653624-312dee9b-7a2e-40de-b723-c70bf4efdd8d.png)
This is the parameter I was used. And my blender framerate was set to
![EP7}DVPVU(TF%L8CLL@NOLU](https://user-images.githubusercontent.com/45847377/134653887-5f33f358-7f81-44f2-a6bc-0d55f1665b70.png)
Before I import Blender. mirv_movie_fps also 30. 
To be honestly, I don't know where I mess it up, Could somebody tell me please?

**Comment by dtugend** [comment]
- remove fps_max 30

- In CS 1.6 host_framerate needs to be fractional / actual frame rate, meaning 1/30 --> host_framerate 0.03333333333333333333
- mirv_recordmovie_start will create a lot of raw tga image files by default in the untitled_rec folder next to hl.exe in Half-Life folder, if that's not wanted, only use host_framerate, otherwise if it is wanted use mirv_movie_fps only.

**Comment by 591280714** [comment]
> * remove fps_max 30
> * In CS 1.6 host_framerate needs to be fractional / actual frame rate, meaning 1/30 --> host_framerate 0.03333333333333333333
> * mirv_recordmovie_start will create a lot of raw tga image files by default in the untitled_rec folder next to hl.exe in Half-Life folder, if that's not wanted, only use host_framerate, otherwise if it is wanted use mirv_movie_fps only.

**Comment by 591280714** [comment]
> * remove fps_max 30
> * In CS 1.6 host_framerate needs to be fractional / actual frame rate, meaning 1/30 --> host_framerate 0.03333333333333333333
> * mirv_recordmovie_start will create a lot of raw tga image files by default in the untitled_rec folder next to hl.exe in Half-Life folder, if that's not wanted, only use host_framerate, otherwise if it is wanted use mirv_movie_fps only.

I set up like u said, still got the problem, But the maximum error changed. I used mirv_movie_fps, the error got much lower, like 
![image](https://user-images.githubusercontent.com/45847377/134695168-df074daa-838b-416c-966c-c2acc6e9eb10.png)
But still has!

**Comment by dtugend** [comment]
what's your exact commands you are using now?

Edit: and what is the maximum error.

**Comment by dtugend** [comment]
Btw the maximum error is so small, that it will only become noticable at 30 FPS in blender after 50 seconds of footage, if it's even noticable*. You should probably consider to ignore it.
also host_framerate 0.03333333333333333333 instead of only host_frameate 0.033 might be better as well (result in smaller mismatch)

Edit:
*Noticable means recorded images and blender would start to mistmatch only then.

**Comment by 591280714** [comment]
> what's your exact commands you are using now?
> 
> Edit: and what is the maximum error.

- mirv_movie_fps 30
- mirv_recordmovie_start
- mirv_agr start "c:\HLAE\Untitled.agr"
I need those tga files so, I used mirv_movie_fps

**Comment by 591280714** [comment]
> Btw the maximum error is so small, that it will only become noticable at 30 FPS in blender after 50 seconds of footage, if it's even noticable*. You should probably consider to ignore it.
> also host_framerate 0.03333333333333333333 instead of only host_frameate 0.033 might be better as well (result in smaller mismatch)
> 
> Edit:
> *Noticable means recorded images and blender would start to mistmatch only then.

so. no matter what, I still get the error, the different is higher or lower?

**Comment by dtugend** [comment]
- There's a small mistake in the script, otherwise it would only warn about errors bigger than 1 ms.
- For technical reasons there has to be always a small error with 30 FPS, since it can not be represented 100% accurately with a float binary value.
- I recommend to set host_framerate 0.33333333333.... as accurate as possible to keep the error as small as possible.

**Comment by dtugend** [comment]
Side note:
The reason that the error doesn't pop for CS:GO but when using mirv_movie_fps in CS 1.6 is that HLAE drives the FPS more accurately / closer to 30 FPS in CS 1.6 than in CS:GO and the import script, that just let the errors add up.

Edit: Probably I should fix the AGR import script to only warn if the absoulte error is >= (1/FPS)/2 (meaning at least half of a frame.

**Comment by 591280714** [comment]
> Side note:
> The reason that the error doesn't pop for CS:GO but when using mirv_movie_fps in CS 1.6 is that HLAE drives the FPS more accurately / closer to 30 FPS in CS 1.6 than in CS:GO and the import script, that just let the errors add up.
> 
> Edit: Probably I should fix the AGR import script to only warn if the absoulte error is >= (1/FPS)/2 (meaning at least half of a frame.

so, your mean is in CS1.6 mirv_movie_fps will do the better work than host_framerate!
and is it host_timescale 0 necessary? I saw this command pop up in https://github.com/advancedfx/advancedfx/wiki/Source:mirv_agr

**Comment by dtugend** [comment]
> so, your mean is in CS1.6 mirv_movie_fps will do the better work than host_framerate!

What I meant is that it tries to maintain the actual FPS closer to a real 30 than CS:GO / Blender themselves.
The problem with that is that the import script / Blender doesn't try the same, that's why _small_ errors happen.

> and is it host_timescale 0 necessary?

No not for CS 1.6, should avoid it there I think. That seems to be a bug in the documentation.

**Comment by 591280714** [comment]
> > so, your mean is in CS1.6 mirv_movie_fps will do the better work than host_framerate!
> 
> What I meant is that it tries to maintain the actual FPS closer to a real 30 than CS:GO / Blender themselves.
> The problem with that is that the import script / Blender doesn't try the same, that's why _small_ errors happen.
> 
> > and is it host_timescale 0 necessary?
> 
> No not for CS 1.6, should avoid it there I think. That seems to be a bug in the documentation.

Well, I guess so. The documentation lied to me~~

**Comment by dtugend** [comment]
The main article for GoldSrc is this:
https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3Amirv_agr

I removed "GoldSrc" from the Source article ( https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_agr ) and pointed it at the GoldSrc article a bit instead.
