### ISSUE TITLE
"Push" the camera towards the object the camera is attached to when it detects clipping with the world

### ISSUE THREAD

**Issue by Markxy** [ripieces/advancedfx#713]
If I'm not missing something, there's no method to detect clipping like this.

Taking the priusfx as examples. With priusfxWeapon, priusfxBack (the easier examples), the camera will clip through walls and sometimes render the whole view black depending on the exact spot on the map.

What I would suggest is: similarly to how the normal 3rd person view works when spectating, if you rotate the camera and there's a wall in the way, the camera gets pushed towards the player. I'm thinking with this solution, it would then be towards the source object instead.

Would it be possible to add such a feature?

**Comment by Markxy** [comment]
To clarify/ give some context: my issue is that doing camera positioning which extends outside of the player (while locking onto a player), it's hard to do in an automated way without many cases where the camera is in a wall.

**Comment by dtugend** [comment]
Hi. Thank your for your feature request. I am currently mostly busy with HLAE 3 when having time and motivation, but I will see if some simple solution with an additional calc will be possible. The problem that the camera has a certain size though will remain, meaning without [much more complicated smart automated camera placement](http://slipgate.de/projects/voronoi.html), it will still run into conflicts at times / be too close too the player model.

Idea would be to make a new vecAng calc that takes two points (camera and player eye position) and sees if there's an intersection with level wall between them and if yes moves to the eye-position / fall back point as much as required + a margin (since the camera has a certain size itself already.

I can not promise if and when though.

**Comment by dtugend** [comment]
I am releasing an update soon, but here is a compile if you know mirv_calcs a bit and want to test already.

But there's only this much this simple method can do if a player stares into a wall for the priusfxFacemask e.g.:
![image](https://user-images.githubusercontent.com/3610128/134758424-555aa38b-131c-4c83-ae90-6d5934474efc.png)

```
[....]
mirv_calcs vecAng add handleAttachment priusfxFacemaskOrigin priusfxObserverTarget facemask
mirv_calcs vecAng add value priusfxFacemaskOffset 11 0 0 0 0 179.9
mirv_calcs vecAng add offset priusfxFacemaskSource priusfxFacemaskOrigin priusfxFacemaskOffset 1
mirv_calcs vecAng add collisionClip priusfxFacemask priusfxFacemaskSource priusfxFacemaskOrigin priusfxObserverTarget 2.0
[....]
```

[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/7229161/AfxHookSource.zip)

**Comment by Markxy** [comment]
@dtugend 
> I can not promise if and when though.

_Proceeds to implement within 24h_

Wow, this is great. Thanks man! I've been playing around with it and it seems to work wonders. 

I have a couple of questions:
- what does the *2.0* variable at the end do?
- is there a way to make the camera's hitbox bigger or add some sort of buffer? Sometimes when it's at an angle from the wall, it's partially showing through the wall. Not a significant issue though 
![image](https://user-images.githubusercontent.com/25804528/134898575-8d08360e-d617-41cb-b172-6a3c1ad609b7.png)

**Comment by dtugend** [comment]
Enter `mirv_calcs vecAng add` for info.
The 2.0 is the safe distance added when there's a clipping point, meaning it pushes the camera closer to the player. As I see now in your case that's not sufficient for steep angles. I would need to make something that takes angle / the surface normal of the surface hit into acount, or if it's possible (need to check) I would need to do a cube trace instead of a ray trace or s.th. like that, or I need more ray traces, not sure yet.

**Comment by Markxy** [comment]
Okay, that makes sense. Thank you!

**Comment by dtugend** [comment]
![image](https://user-images.githubusercontent.com/3610128/135577848-7ae0a272-ab16-4ddd-be50-8fe1c98dc087.png)
- need to extend trace_end to maximal traceable distance, since with steep angles hit can be in infinity but safe zone very close.

- https://en.wikipedia.org/wiki/Intercept_theorem
```
||(1-t) * ray_dir|| : ||ray_dir|| = safe_dist : ||PO-hit||
1-t = safe_dist : ||PO-hit||
PO - projection of origin onto surface P
```
- https://math.stackexchange.com/a/100783
```
PO = origin + ray_dir - (ray_dir \dot plane_normal) / ||plane_normal||^2 * plane_normal

1 - t = safe_dist / ||-(ray_dir \dot plane_normal) / ||plane_normal||^2 * plane_normal||
```
```
PO = origin + ray_dir - (ray_dir \dot plane_normal) / ||plane_normal||^2 * plane_normal

1 - t = safe_dist / ||-(ray_dir \dot plane_normal) / ||plane_normal||^2 * plane_normal||
```

**Comment by dtugend** [comment]
Hi here is the new version, I recommend a safe zone of more than sqrt(98 units) (e.g. 10.0, which is equivalent to 12/16inch * 10 = 7.5 inch), 2.0 is too small.
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/7271308/AfxHookSource.zip)

This will still clip through walls in some situation, since it only does one ray trace.
This could be further improved e.g. by doing 4 more traces to each "edge" of the safezone.

I am not sure if this is currently required, since it will slow down other work for HLAE, but 4 more traces would improve notably probably, while more than 5 total won't imporve that much with reasonable small safezones of around 10.0.

**Comment by Markxy** [comment]
Hey @dtugend !
Sorry for taking so long to get back to you.

I tested this version. Overall it looks quite good!

When I tested the scenario above again, the safezone looks to kick in after the clipping occurs, it feels like.
Are there any configurations I can alter or is this to do with something inherent like interpolation? This might be an extreme case too because the player goes right-left-right, changing the moving direction rapidly. And I don't want to burden you with this if it's too troublesome to deal with. I'm happy with the results that are already there.
Here's the example again: (don't mind the screen capture)

https://user-images.githubusercontent.com/25804528/136944017-ba9e20e0-272e-4e78-a6c6-324b518829c0.mp4

**Comment by Markxy** [comment]
To clarify/add additional info: with the first iteration it would simply track the wall and show through the wall for a longer time (like my first image above). Now, in that video, it seems to "correct" itself after clipping.

**Comment by dtugend** [comment]
Hi. I have tested against the same wall actually earlier already.
It's clipping corectly.
The reason is that it's clipping against only 1 ray, which happens to go through the center of screen.
So in this case as the player gets close to the wall at a steep angle the right outer side of the camera starts clipping through already, but the 1 center ray still doesn't hit the wall yet.
As it gets closer it hits it and is corrected.
As the player moves away the opposite happens.

That's why I planned to add 4 more rays for each corner of the safezone, that would mostly fix it, apart from super rare other corner cases that would need even more rays or a different technique.

Thank you for testing, apparently the problem is still to common with only 1 ray, so I will try to implement the 4 other rays when I have time, before the feature is officially released.

**Comment by dtugend** [comment]
> Add more rays to collision clip
> 
> - Recommended safeZoneDist value for camera is 7 units (7*12/16 inch),
>   which also is approximately the near plane distance of the camera on default
>   FOV I think.
> - This works better than expected, there can be some rare corner cases where it
>   switches quickly between clipping and not clipping, maybe a smooth
>   calc on the output can dampen that a bit (at least for convex cases it
>   should dampen it in a fine way, for concave cases not so much I
>   guess).

If you want to test before upcoming release:
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/7398218/AfxHookSource.zip)
