### ISSUE TITLE
Metadata Withdraw Command

### ISSUE THREAD

**Issue by Purple-CSGO** [ripieces/advancedfx#761]
Request for adding commands that withdraw neccessary **timecode-based metadata** for post data generation sync to the clip, Then tools can be made to **generate** deathmsg / crosshair / soundtrack **afterwards** without worrying about recording i.e. seperate HUD

- HUD metadata
- deathmsg (fragger, weapon, victim, headshot, etc)
- weapon state (player is currently using AK/AWP/... , scoping, etc)
- sound metadata (weapon shooting, clipping, hitting, etc)  with filters that keep frequently used sounds
> for dealing with soundtrack when speed ramping

**Comment by dtugend** [comment]
This seems to be a duplicate or superset of #387, closing that one in favor of this one.

**Comment by dtugend** [comment]
Hi.

A small part of this is possible now in CS2 with mirv-script over the websocket interface it has. Not sure how much more we will get of this feature request though.

Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
