### ISSUE TITLE
mirv_pov broken scope hud overlay?

### ISSUE THREAD

**Issue by Markxy** [ripieces/advancedfx#769]
Seems if i have the skiptotick command too early in the `.vdm` file, the scopes would become broken like in this image:
![image](https://user-images.githubusercontent.com/25804528/169543766-47e5b92c-b893-48c6-b5de-68e80b02e83a.png)

Vdm contents:
```
"demoactions"
{
	"1"
	{
		factory	"SkipAhead"
		name	"SkipAhead8"
		starttick	"1"
		skiptotick	"171000"
	}
	"2"
	{
		factory	"PlayCommands"
		name	"spec"
		commands	"demo_togglepause"
		starttick	"171100"
	}
}
```

If it's like this, it behaves as normal:
```
"demoactions"
{
	"1"
	{
		factory	"SkipAhead"
		name	"SkipAhead8"
		starttick	"500"
		skiptotick	"171000"
	}
	"2"
	{
		factory	"PlayCommands"
		name	"spec"
		commands	"demo_togglepause"
		starttick	"171100"
	}
}
```

Command i launch CSGO & HLAE with:
`& "E:\HLAE\HLAE.exe" -csgoLauncher -noGui -autoStart -csgoExe "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo.exe" -gfxEnabled true -gfxWidth 1920 -gfxHeight 1080 -gfxFull false -customLaunchOptions '-steam -game csgo -insecure -allow_third_party_software -applaunch 730 -novid -console +mirv_pov 11 +playdemo "E:\demos\1-bd5a4dec-73df-40f3-ac84-23db8ddf5cd6-1-1.dem"'`

[dropped the demo and vdm into drive](https://drive.google.com/drive/folders/16X-D1qjH91tQFWxraNUoA4YIiXPO2Al2?usp=sharing)

It seems to be always happening with mirv_pov and on very different computers too.

Do you have any ideas/suggestions? Waiting some time when the demo loads seems to do the trick, but maybe there's a better way.

**Comment by dtugend** [comment]
I doubt that problem is mirv_pov specific.

I am guessing it can be reproducted without mirv_pov and with
cl_obs_interp_enable 0
spec_player / spec_player_by_accountid  
and only after that skip and so on.

In that case I would not be keen on fixing Valve's code for that case.

Maybe it would work already if you don't skip before tick 10 or 20, if I am remembering correctly, the demo does quite some things on / close to tick 1.

**Comment by Markxy** [comment]
Hmm ok I'll try to replicate without mirv_pov.
It may be demo-specific too, this one is a FACEIT demo.

I tried skip at tick 256 (2s) but had the same effect.

**Comment by dtugend** [comment]
You mean it was still broken, even when skipping from 256?

When I have time and motivation I will try to look into it.

The problem is I know from threads on reddit, that this bug even happens in live games at times, so that's why I am confident it's not just simply a mirv_pov bug / problem.

**Comment by Markxy** [comment]
Yes, 256 didnt work and 500 worked.

You're probably right, but could it be that with mirv_pov the threshold for this happening is higher because in my use cases I havent noticed this without it.

**Comment by dtugend** [comment]
Before recording execute these commands (e.g. before you do demo_togglepause):
```
gameui_activate;gameui_hide;hud_reloadscheme
```

1. `gameui_activate` and `gameui_hide` take care of hiding the teamselect menu, which can appear with mirv_pov in some cases when the player is not connected, especially when demo_index feature is on 1 (btw you might want to enable that feature if you record more than 1 pass on a demo, otherwise keep demo_index 0).
2. `hud_reloadscheme` fixes the vgui panel sizes (the HUD panel is wrongly sized when the bug happens.

Please close this issue if your problem is solved by that.

----

```
"demoactions"
{
	"1"
	{
		factory	"SkipAhead"
		name	"SkipAhead8"
		starttick	"1"
		skiptotick	"171000"
	}
	"2"
	{
		factory	"PlayCommands"
		name	"spec"
		commands	"gameui_activate;gameui_hide;hud_reloadscheme;demo_togglepause"
		starttick	"171100"
	}
}
```

**Comment by Markxy** [comment]
@dtugend Works like a charm! Appreciate it, thanks! :)
