### ISSUE TITLE
Better in-game load demo experience

### ISSUE THREAD

**Issue by Purple-CSGO** [ripieces/advancedfx#773]
Currently, If we want to load a demo ingame, we have to use demoui and select directories multiple times, from each time. It is kind of painful. I'm suggesting adding a command setting current demo directory and enabling playdemo command with only the demo name. Furthermore, a better wrapped playdemo command?

**Comment by Dechno1337** [comment]
Doesn't playdemo support directories as well? `playdemo replays\demoname.dem`(?)

**Comment by Purple-CSGO** [comment]
yes, but suffix directory path is not convenient enough to use and memorize, especially dealing with multiple demos. So If we have a specific demo dir for current project, it is easier cuz we can configure the working dir in cfg.

**Comment by Dechno1337** [comment]
Is this still neccessary for CS2?

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
