### ISSUE TITLE
cs 1.6 agr visibility bug?

### ISSUE THREAD

**Issue by instincthns** [ripieces/advancedfx#780]
agr appears, but does not disappear back
https://www.youtube.com/watch?v=zVZCtoamb54

**Comment by dtugend** [comment]
I can confirm there's a bug:
The first afx.16.w_deagle is correct I think, since it's the end of the demo and is still on the ground, so it has to be visilbe.
But the second afx.8.p_deagle is bugged for sure.

The source of the problem is that that the same entity has multiple possible models (e.g. p_ for worn person model, w_ for world model). I have yet to decide if this is a problem of the AGR export or the AGR import plugin.

**Comment by dtugend** [comment]
Is it possible for you to compress the AGR file and provide a download of it, please?

**Comment by instincthns** [comment]
> Is it possible for you to compress the AGR file and provide a download of it, please?

https://dropmefiles.com/wLsiD

**Comment by dtugend** [comment]
Thank you for reporting the issue, I hope this solves it:
https://github.com/advancedfx/advancedfx/releases/tag/v2.132.1

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/9057265/AfxHookSource.zip)

**Comment by dtugend** [comment]
sorry uploaded wrong file in last comment:
[AfxHookGoldSrc.zip](https://github.com/advancedfx/advancedfx/files/9057286/AfxHookGoldSrc.zip)

**Comment by dtugend** [comment]
[AfxHookGoldSrc.zip](https://github.com/advancedfx/advancedfx/files/9057435/AfxHookGoldSrc.zip)

**Comment by dtugend** [comment]
[AfxHookGoldSrc.zip](https://github.com/advancedfx/advancedfx/files/9057477/AfxHookGoldSrc.zip)

**Comment by dtugend** [comment]
[AfxHookGoldSrc.zip](https://github.com/advancedfx/advancedfx/files/9057557/AfxHookGoldSrc.zip)
