### ISSUE TITLE
Add Steam CSS version agr support 

### ISSUE THREAD

**Issue by WitherSkell** [ripieces/advancedfx#784]

**Comment by dtugend** [comment]
Hi, this is already available since HLAE 2.128.1 (2022-04-15T13:44Z), I jut forgot to document it in the Wiki (documented now).

It works the same as for CS:S v34, meaning don't forget to set `mirv_agr enabled 1` before loading the demo!  
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_agr#csgo-css-css-v34-tf2

**Comment by WitherSkell** [comment]
Thank you!
