### ISSUE TITLE
Language Switching Feature

### ISSUE THREAD

**Issue by Purple-CSGO** [ripieces/advancedfx#788]
Currently hlae chooses the language according to the system, but users might want to switch to a different language (e.g. not satisfied with the translation)

**Comment by dtugend** [comment]
As a workaround in case English is wanted you can currently delete / empty the locales folder that comes with the ZIP or choose to not install translations in HLAE_Setup.exe advanced options (however the installer will start in the unwanted langauge).

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
