### ISSUE TITLE
gaussian frame blending like srcdemo2

### ISSUE THREAD

**Issue by abandonedpools** [ripieces/advancedfx#795]
Not really sure how to explain it simply/clearly but it's a way of weighing the frames that go into a sampled frame, based on a gaussian curve. A setting to change how much this "effect" is applied would also be nice (like in the screenshot).

![Screenshot_28](https://user-images.githubusercontent.com/95392381/192625536-86ea549a-0694-44a0-b0a3-b308608bca8e.png)

**Comment by Dechno1337** [comment]
If the HLAE GUI ever sees the light of the day, it would make sense to have these similar options. 😄

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
