### ISSUE TITLE
Mirv_pgl Causes the Game Running Sluggish

### ISSUE THREAD

**Issue by DuKeM-CSGO** [ripieces/advancedfx#796]
When _mirv_pgl_'s websocket client losing its connection to the server, just like the server process is killed, it seems that the client falls into a endless loop, waiting for the response of that runaway server. What's happening in the game is, the framerate(even at the main menu) decreases and it's hard to type any words(e.g.`mirv_pgl stop`) into the console.Maybe it needs a more improved mechanism to deal with the runaway server.

**Comment by Dechno1337** [comment]
Isn't this obsolete now with the release of CS2(?)

**Comment by dtugend** [comment]
> Isn't this obsolete now with the release of CS2(?)

Not exactly https://github.com/advancedfx/advancedfx/issues/867

**Comment by Dechno1337** [comment]
> Not exactly

Even if you were to port it over to CS2, are you certain it would still have this issue in the different engine? 🤔 We/you could temporarily close this thread, and only re-open it if this issue still persists if/when you add this feature to CS2?

**Comment by dtugend** [comment]
Hi.

In CS2 this might be replaced by mirv-script in the future: https://github.com/advancedfx/advancedfx/tree/main/misc/mirv-script

Otherwise thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
