### ISSUE TITLE
depth bug with 7900 XTX GPU

### ISSUE THREAD

**Issue by Markxy** [ripieces/advancedfx#820]
I'm having this weird depth bug after switching from Nvidia to the new AMD gpu.

Viewmodel and some other rendered object types are affected.
It seems it's just the method that HLAE is getting the depth data, as the in-engine (and also Reshade's own) depth seems to not have this issue.

Example:
https://user-images.githubusercontent.com/25804528/212319466-cb9a2002-9496-4a3a-9100-42cbb5993033.mp4

To reproduce:
```
mirv_streams add depth myD
mirv_streams preview myD
```

**Comment by dtugend** [comment]
Unbindinding INTZ depth stencil texture for the depth buffer fixed it, though accoridng to AMD's / former ATI's own documentation (https://developer.amd.com/wordpress/media/2012/10/Advanced-DX9-Capabilities-for-ATI-Radeon-Cards_v2.pdf) we shouldn't have to do this, since we have depth writes disabled (D3DRS_ZWRITEENABLE = FALSE):

> Note that an INTZ depth buffer may be used as a texture concurrently to the same INTZ
> surface being used for depth buffering, as long as depth writes are disabled.

, but apparently it stoped working on the 7900 XTX GPU, while it works fine with NVIDA GPUs still.

Maybe someone bored can fille a bug report with them, or maybe I misunderstood s.th. I dunno.

Many thanks for patience when testing @Markxy !
