### ISSUE TITLE
GoldScr Time Event problem

### ISSUE THREAD

**Issue by 591280714** [ripieces/advancedfx#829]
In event list time can not be specific..
![image](https://user-images.githubusercontent.com/45847377/221903170-778b079d-839f-4d96-a337-69d4767a2b86.png)
When I changed the number from 67 to 68, would have liked this:
![image](https://user-images.githubusercontent.com/45847377/221903597-545b5231-c994-4659-ad58-75b90932cf16.png)
still appeared 67,
But when I had changed to 69, It appeared normally:
![image](https://user-images.githubusercontent.com/45847377/221903800-e870ccde-d7e6-4275-a246-38b9a3aefb3b.png)
It seems like some times will ignore some specific setting? In this case it just skips number 68.. can be fixed?

**Comment by dtugend** [comment]
1. DemoUI is by Valve not by HLAE.

2. This is a 32 bit IEEE single precision floating point number precision problem:
The number is encoded to seconds, in decimal encoding it would be `239.68`, which is encoded `14 AE 6F 43` as 32 bit IEEE single.
If you decode this you get about `239.679992675781` which is rounded down when displayed, an error of  about `-0.000007324219`.
The next possible higher number is `14 AE 6F 43` is about `239.68000793457`, an error of about `0.00000793457`, which is significantly worse.

So because the number is rounded down in the GUI, you see an error of 1 millisecond, but it's actually much less.

**Comment by 591280714** [comment]
> 1. DemoUI is by Valve not by HLAE.
> 2. This is a 32 bit IEEE single precision floating point number precision problem:
>    The number is encoded to seconds, in decimal encoding it would be `17.768`, which is encoded `DD 24 8E 41` as 32 bit IEEE single.
>    If you decode this you get about `17.7679996490479` which is rounded down when displayed, an error of  about `-0.0000003509521`.
>    The next possible higher number is `DE 24 8E 41` is about `17.7680015563965`, an error of about `0.0000015563965`, which is significantly worse.
> 
> So because the number is rounded down in the GUI, you see an error of 1 millisecond, but it's actually much less.

So, You mean when I type 68 inside, It will be 67.768? so it appeared 67?

**Comment by dtugend** [comment]
I used the wrong numbers above, I will edit in the correct ones later.

I am not 100% sure, one would have to test it, but if I remember correctly then yes, it uses the number derived from the typed one and not the one displayed rounded down.

**Comment by dtugend** [comment]
But be careful. If you edit and save it again, it will use the worse number!

**Comment by dtugend** [comment]
I close this for now, I hope it's ok.
