### ISSUE TITLE
FFmpeg recording for TF2

### ISSUE THREAD

**Issue by 01230123abc** [ripieces/advancedfx#836]
I believe, it's a good idea to support FFmpeg recording in TF2, since it's very fast, easy to setup and it doesn't take many resources.

Thanks!

**Comment by Dechno1337** [comment]
HLAE doesn't have a recording system for TF2 though? If HLAE had one (`mirv_streams` for example) then I assume it would be fairly easy to implement, but it doesn't. 😐

**Comment by dtugend** [comment]
working on it (only screen capture)

TODO:
- startmovie front-ending for audio.wav if possible
- fix FPS detection not being possible by providing an option to set FPS

**Comment by dtugend** [comment]
If someone wants to test, you can use this on-top of latest HLAE: 
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/11642406/AfxHookSource.zip)
Or build the branch ffmpeg-other-836

```
host_framerate 1200; mirv_streams record fps 1200; mirv_streams record screen enabled 1; mirv_streams record screen settings afxFfmpegYuv420p; mirv_streams record start
// ...
mirv_streams record end
```
(This should work in a demo, when testing live in-game you will need to enter `sv_cheats 1` before that.)

While this works on CS:GO too, it's not recommended there, since a "normal" stream should be a tiny bit faster and cleaner.
(This should work for several mods with Direct3D9, not only TF2.)

Edit: Note: Since this frontends startmovie wav for audio, you will need to close console / resume into game, unless you are using CS:GO.
