### ISSUE TITLE
MIRV_CAMPATH 

### ISSUE THREAD

**Issue by eGabox** [ripieces/advancedfx#841]
Hello, I have a question, I am new to using HLAE, I would like to know if the MIRV_CAMPATH commands can be used in CSGO and also in CS 1.6, or if they work differently in each one.

**Comment by Dechno1337** [comment]
`mirv_campath` was added to GoldSrc a few years ago, but with fewer features I think.

Source:
https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_campath

GoldSrc:
https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3Amirv_campath

Before `mirv_campath` was added to GoldSrc, there was DemoEdit which was a hidden built-in tool, but now I guess it's mostly obsolete since `mirv_campath` might be more convenient:
https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3ADemoEdit

**Comment by eGabox** [comment]
> `mirv_campath`se agregó a GoldSrc hace unos años, pero creo que con menos características.
> 
> Fuente: https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_campath
> 
> GoldSrc: https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3Amirv_campath
> 
> Antes de que `mirv_campath`se agregara a GoldSrc, había DemoEdit, que era una herramienta integrada oculta, pero ahora supongo que en su mayoría está obsoleta, ya que `mirv_campath`podría ser más conveniente: https://github.com/advancedfx/advancedfx/wiki/GoldSrc%3ADemoEdit

Thank you very much, I think I have a lot to read to learn its use
