### ISSUE TITLE
mirv_campath draw enabled 1 for Left 4 Dead 2?

### ISSUE THREAD

**Issue by RichardHafer** [ripieces/advancedfx#858]
I know this tool is mainly for CSGO, but I'm still gonna report this just in case. 
Left 4 Dead 2 seems to crash every time when trying to see the campath keyframes. Everything else seems to work fine.

**Comment by Dechno1337** [comment]
It's not supported in L4D2 so technically it's not a bug.

Let's see what dtugend has to say. 🙂🙏

**Comment by dtugend** [comment]
Hi, it's not obvious from the Wiki, but HLAE supports more games with campath then it does with drawing the path sadly.
I thought I used to have a free version of L4D2, but somehow it was revoked it seems, so I can not really look into it myself:
If you could check if L4D2 uses the old Direct3D 9, that could help, because if it uses s.th. newer HLAE (currently) can't do that.

**Comment by RichardHafer** [comment]
Hello. Left 4 Dead 2 uses DirectX Version 9.0 as far as i know. However
Vulkan is also Supported and can be switched to with launch option.

I assume you only had l4d2 from a free-weekend. Unfortunately you don't
keep the game permanently from those.

Dominik Tugend ***@***.***> schrieb am Do., 13. Juli 2023,
10:18:

**Comment by dtugend** [comment]
Hi.

First make sure you are using the latest HLAE version available for download (stable).

Please first make sure it's really using Direct3D9. If it still crashes:
Please make it crash, then look for a mdmp or dmp file from the time it crashed in:
C:\Program Files (x86)\Steam\dumps
**Edit: or l4d2.exe folder**
Also include a copy of the client.dll of the game (l4d2/bin folder) engine.dll and tier0.dll and if available tier1.dll (bin folder), please.
Compress it please e.g. with https://7-zip.org/ and share with contact@advancedfx.org (you can share Google drive with that too btw).
Please do not share publicly since the crashdump can contain sensitive information.

With this information I can take a look at it and see if I can figure out s.th. already to fix it, or if it's not possible.

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/12052300/AfxHookSource.zip)

@Dechno1337 when you have time, can you test this DLL with L4D2 please?

Also please test if mirv_campath outputs the correct demo tick and time if possible, pelase (only if you can).

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/12052696/AfxHookSource.zip)
@Dechno1337 this one should be better

**Comment by dtugend** [comment]
[AfxHookSource.zip](https://github.com/advancedfx/advancedfx/files/12053044/AfxHookSource.zip)
@Dechno1337

**Comment by dtugend** [comment]
It should work now: https://github.com/advancedfx/advancedfx/releases/tag/v2.146.1
