### ISSUE TITLE
CS2: mirv_pov 

### ISSUE THREAD

**Issue by 21161107** [ripieces/advancedfx#875]
it's really necessary to get this chievements

**Comment by Dechno1337** [comment]
(CS2 I assume)

**Comment by dtugend** [comment]
This was very complicated hook-wise in CS:GO and only possible due to access to older CS:GO source code.
Meaning don't expect it (any time) soon for CS2 to be honest, sorry.

**Comment by ar1a** [comment]
I would really *really* like to see this reimplemented for cs2. Hopefully we can figure out a way at some point

**Comment by ezridvan** [comment]
is there no way to watch the demo the way the player sees it? I've been doing this with mirv_pov before.

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
