### ISSUE TITLE
CS2: mirv_ commands do not work randomly

### ISSUE THREAD

**Issue by Purple-CSGO** [ripieces/advancedfx#887]
- Latest HLAE release
- Setup using [preset cfg](https://github.com/Purple-CSGO/CS2-Config-Presets/blob/master/hlae.cfg)
- Sometimes it does not work, after re-launch with hlae it works

## Wait for testing
- [ ] Setup Check with single command: `mirv_input camera`

**Comment by dtugend** [comment]
Can you provide more details, please:
- When is the command entered (before loading the map, in-game, ...)?
- In which way it exactly doesn't work (how do you notice, what do you expect, what happens)?
- If it doesn't work, does the console print something (We had a case where for one person the console would print mirv_input help instead of doing mirv_input camera, but I could never reproduce it.)?
