### ISSUE TITLE
IOSoccer Support

### ISSUE THREAD

**Issue by FrazerOR** [ripieces/advancedfx#927]
I know it's probably an unrealistic expectation (especially for something so niche) but there's no harm in asking

https://store.steampowered.com/app/673560/IOSoccer/

**Comment by dtugend** [comment]
It's unlikely we will add support (because of #896) but we will keep it open for now.

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
