### ISSUE TITLE
CS2: Camera Swapped when adding new one

### ISSUE THREAD

**Issue by Purp16** [ripieces/advancedfx#932]
## Problem

When Adding CAM 1 -> CAM 2 -> CAM3, CAM 3 & 2 are swapped, causing the camera path zigzagged

Suspecting that it's the latest cs2 update that breaks the functionality.

## Workaround

Do not place key-frames while the demo is paused.

## Video

https://drive.google.com/file/d/1fdGUavezxPA_TpNyjBS6HKzahn3WQGCp/view?usp=sharing

<img width="989" alt="image" src="https://github.com/advancedfx/advancedfx/assets/96715101/a776d877-e68c-42e7-9dff-a2142c7f8798">

<img width="765" alt="image" src="https://github.com/advancedfx/advancedfx/assets/96715101/71e59327-a9af-4c8f-aad9-224bc91b86d1">

## Reproduce

- [x] Reported: Once with a video shown above
- [ ] Reproduce: Not Tested yet

**Comment by dtugend** [comment]
![image](https://github.com/advancedfx/advancedfx/assets/3610128/c6bd8d4c-ee48-4cda-902a-04075ff3cad1)

Multiple people tried. We are unable to reproduce the problem on the version ` Apr 25 17:29:1 - S`
![image](https://github.com/advancedfx/advancedfx/assets/3610128/a0619778-fd89-4b1f-a5b6-54334bbe992e)
(Edit: the version in the video seems to be different: ` Apr 25 17:29:1 - R`)

Please first make sure the game is fully updated and verify game cache, if it still happens after that please let us know:

- if it happened on
 - CSTV
 - Demo
 - ListenServer spectator slot
- tickrate of server (64 or 128?)
- Is it an old demo or recent demo?
- Your exact game version

**Comment by ChetdeJong** [comment]
I was able to re-produce the issue and there's more to that. Check video below.

The issue is not only with campath swap, but I think it's more related to game time.
In the update they changed something so you can fly when demo is paused, without `mirv_input camera`

So now if you add campath point when demo is paused, then time is shifting. 
You can see that in `mirv_campath print` and you see it also by campath visual color.
Note that `current gameTime` is changing when demo is paused, as well as campaths points time.

I tried to put campath points when demo is not paused, resulting into campath swap and time shift.
_Edit: I think its likely because I placed one points when it was paused, so it used wrong time. Check my next comment._

Not sure should I open different issue for that. 
Also not sure if there is fix for that since that is game "feature" now.

Video: 
https://youtu.be/UQf6On0qi-Y

Latest CS2 and HLAE.
Demo recoded after update on same game version.
Exact game version could be seen in video.

**Comment by ChetdeJong** [comment]
I did more testing. 

Interesting that when demo is paused the game time goes, but when demo is resumed it jumps back to previous position. 
So placing campaths when demo is not paused seems fine, but it just destroys work flow.

Possible solution:

Capture the game time in the moment, when demo is being paused (pause button pressed) and use that time internally to use it for placing campath, displaying current time, etc. So doesn't matter if game time goes, HLAE should just cache it.

**Comment by dtugend** [comment]
Can reproduce the bug when pausing. Solution will probably be related to what @ChetdeJong suggested.

**As a workaround unpause the demo before placing the keyframe.**

I probably won't have time to fix it before 6 - 12 hours from now.

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/releases/tag/v2.159.0
