### ISSUE TITLE
Add support for Military Conflict: Vietnam (mcv \ 64-bit)

### ISSUE THREAD

**Issue by sashiezzz** [ripieces/advancedfx#934]
This game is really fun, has people playing (low population but will change in the future), and is actively being updated. It's 64 bit and it's based off the source code of CS:GO (license given by Valve) but modified a lot by now seeing HLAE support for this game would be nice since it has a lot of potential as a game and to edit too. It's paid starting at $9.99 but if you do end up making support for this game I can get you access to the game for free. Please let me know if so. If you have any other questions please let me know too.

https://store.steampowered.com/app/1012110/Military_Conflict_Vietnam/

**Comment by dtugend** [comment]
It's unlikely we will add support (because of #896) but we will keep it open for now.

**Comment by dtugend** [comment]
Hi. Thank you for your suggestion. The implementation of this feature in a reasonable time-frame is currently not realistic for me. After considering that together with issue #896 I am closing this request as not planned for now, since it would block other things I would like to still get done before that. Sorry for the copy pasta.
