### ISSUE TITLE
campath.xml to output folder

### ISSUE THREAD

**Issue by eirisocherry** [ripieces/advancedfx#964]
Saving a campath manually clogs up the game folder, you always need to make unique names and sometimes you just forget to save it  

This feature will make cinematic rerecording much easier:  
`mirv_streams record campath enabled 0/1` Controls the campath data capture output  

![Screenshot_4](https://github.com/user-attachments/assets/93a52e22-65c3-47ae-bb53-05d4afd4c942)

**Comment by ChetdeJong** [comment]
I'm not sure if it makes much sense to trigger it specifically on record. 

Previously you suggested autosave in other issue, which makes sense https://github.com/advancedfx/advancedfx/issues/895. Also there was suggested workaround to bind campath save with other related things. So in this case you can do basically the same.

 _Note: you can also provide path instead of filename e.g. mirv_campath save "C:\campaths\mycampath.xml"_

The issue then would be having unique names like you mentioned. The better thing imo would be adding option to generate unique name when you [save campath](https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_campath#saving-a-path-to-a-local-file).

**Comment by eirisocherry** [comment]
i dont want to generate and remember campath names for my 50+ cinematics
i just want it to be saved to the recording folder, so if i want to rerecord it i simply copy paste the campath into the game folder and immediately rerecord it

also it may be helpful for people i share my clips with, so they can easily use my campaths without wasting time trying to figure out which one is the right one

**Comment by ChetdeJong** [comment]
Well I don't see the problem with having a bind.

e.g. `bind "f9" "mirv_streams record start; exec save_campath"`. In `save_campath.cfg` you might have `mirv_campath save "C:\path\to\output\folder\campath.xml"`. Separate cfg file is needed due extra quotes. Then just have your recording done and drop xml to take folder. This is less convenient rather than having it done automatically, I agree.

That said I'm still not sure if this needed to be implemented (or at least implemented this way).

@dtugend what do you think? If that's ok I can put up PR for this, when I have time

**Comment by dtugend** [comment]
I planned to do something regarding this for CS2 using mirv-script, but we noticed you are using CS:GO hm.

**Comment by gotersyt** [comment]
I think this will greatly simplify and speed up recording flights. IMHO you don’t always save the curve, but if you forgot to record the required layer, then what? record again for a couple of hours?

**Comment by dtugend** [comment]
Will try to support this through a mirv-script snippet, but that means it will only work in CS2.

**Comment by eirisocherry** [comment]
ah, cs2 is not editing ready, i'd like to see the feature in csgo

is it hard to implement? i thought you could just copy-paste the code of `mirv_streams record cam enabled 1/0` command
and adjust it so it works as `mirv_streams record campath enabled 0/1`

sorry if i'm wrong 🙏

**Comment by dtugend** [comment]
Well it's not exactly like that, but it indeed is simple / low hanging fruit, compared to other stuff. Might look into it myself, but can't promise right now.
