### ISSUE TITLE
CS:S on CS:GO engine support

### ISSUE THREAD

**Issue by SHUTDOWNOfficial** [ripieces/advancedfx#975]
Hello, would support for this be hard to implement? Maybe it would make stuff like depth map and hud streams in CS:S possible?
https://www.youtube.com/watch?v=-SKjuLDYQcI

**Comment by dtugend** [comment]
I don't have plans to support this specific modification (and I can't comment on if it's safe to use or not), however, since it is based on the original CS:GO engine, chances are that one of the (recent or older) HLAE versions will work, which one depends on the CS:GO version you use.

E.g.:
- if using latest CS:GO (steam_legacy beta of CS2), try the [latest HLAE](https://github.com/advancedfx/advancedfx/releases/latest)
- if using same version like Zool's Classic Offensive mod try [HLAE 2.140.0 (2022-10-07T18:28Z)](https://github.com/advancedfx/advancedfx/releases/tag/v2.140.0) instead


To launch from HLAE you will need to install and launch once without HLAE and then use this procedure:

---

Start HLAE.exe.

Open the custom loader: <tt>HLAE -> Menu -&gt; Tools -&gt; Developer -&gt; Customloader</tt>

* HookDLL: select the <tt>AfxHookSource.dll</tt>
* ProgramPath: select the csgo.exe in the modified <tt>..\Steam\steamapps\common\Counter-Strike Global Offensive</tt> folder (where you installed the modification).
* CommandLine: <tt>-steam -insecure +sv_lan 1 -window -console -game cstrike -afxGame csgo</tt>

Click okay.
If launching was successful you should see a console message by advancedfx.org.

Don't join any VAC protected servers, that might get you VAC banned.

**Comment by SHUTDOWNOfficial** [comment]
Thank you so much! I tried launching in both versions and get a bunch of errors in:
addresses.cpp:257,301,369,406,457,541,584,634,658,685,737,769,3173
I'm guessing that means it won't work?

**Comment by dtugend** [comment]
As said it depends which CS:GO version you are using, which one are you using?

**Comment by dtugend** [comment]
If you get the same errors for both, chances are you launched the same one twice.

You will have to use the .zip version, installer version will only work if you uninstall the current one first before installing an older one.

**Comment by SHUTDOWNOfficial** [comment]
I used the zip versions for both, yeah. As for the CSGO version, the creator said he used the 2020 engine leak version, but I'm not quite sure beyond that as I am not familiar with the leaks.

**Comment by dtugend** [comment]
Then you will need an way older HLAE.
You could start the game without HLAE once and enter `version` into console to get more information.

**Comment by SHUTDOWNOfficial** [comment]
It looks to me like it's more CS:S related weirdly enough.

Protocol version 6630498 [6630498/6630498]
Exe version 6630498 (cstrike)
Exe build: 17:48:01 May 30 2024 (4842) (240)

According to Valve themselves the 2020 leak build is from late 2017, so maybe a version from that time period would be appropriate?

**Comment by dtugend** [comment]
The download looks as if it's a custom build based on the leaked source, so it might not work with any HLAE version, since it will be different from any official past CS:GO version probably.
Sorry that I didn't notice this earlier.

I don't know which version the leak is based on, but if it was not a custom compile you could try
- https://github.com/advancedfx/advancedfx/releases/tag/v2.44.0
- https://github.com/advancedfx/advancedfx/releases/tag/v2.79.0

But as said above, since they probably compiled the source themselves and modified it it will not work either way, sorry.

**Comment by dtugend** [comment]
> It looks to me like it's more CS:S related weirdly enough.

Not only that, it also reminds me suspiciously of this CSS modification from 2022:
https://www.moddb.com/mods/counter-strike-source-offensive

As said I can't comment if the one you found is safe to use or not, I simply didn't check / don't know.

**Comment by SHUTDOWNOfficial** [comment]
From my experience it's safe, you have to create symlinks to an actual CS:S install to be able to play it. I've never seen that mod, that's interesting... 
I guess you pretty much concluded it there, the furthest I got (with 2.44.0) is being able to load into the menu with the mirv commands working, but loading into any map crashes the game.
Thank you so much for helping out!
I don't suppose there is any way I missed to capture viewmodels with mirv_agr or separate the HUD in any of the actual CS:S versions?

**Comment by dtugend** [comment]
> From my experience it's safe, you have to create symlinks to an actual CS:S install to be able to play it.

That is correct, but it inlcudes own .exe and .dll files that will be used, so it depends on if you trust that person or not.

> I guess you pretty much concluded it there, the furthest I got (with 2.44.0) is being able to load into the menu with the mirv commands working, but loading into any map crashes the game.

You can find older and newer HLAE versions here ( but as said probably none will work, so might be waste of time ):  
https://github.com/advancedfx/advancedfx/releases?page=21 
To avoid having to test every single version open AfxHookSource_changelog.xml that comes with newest version and only look out / search for "Adjusted" "CS:GO update" or similar keywords, to only test the last version before such a new version.

> I don't suppose there is any way I missed to capture viewmodels with mirv_agr or separate the HUD in any of the actual CS:S versions?

As far as I know HLAE AGR can capture viewmodels in official CSS / versions supported by HLAE with AGR, but that would be a question for @Devostated, he might remember better than me. I also don't remember if you could capture all viewmodels with a trick or only the in-eye one, devo might know.

HLAE has no mirv_streams support for CS:S, but I think there's a trick to only capture the HUD and have the rest green or black, maybe it can be answered by someone else in [HLAE Discord](https://discord.gg/NGp8qhN) or [Devo's discord](https://discord.gg/wd8Rcdj), I don't remember that either sorry.

**Comment by Devostated** [comment]
Hey, HLAE should support the AGR feature for CSS Steam and v34.

**Comment by dtugend** [comment]
We are in Discord now, original issue remains unsolved however.
