### ISSUE TITLE
GoldSrc: ffmpeg recording gets unflipped results

### ISSUE THREAD

**Issue by Purple-CSGO** [ripieces/advancedfx#983]
## Problem

As reported, without manually adding flip filters, the video need to be vertically and horizontally flipped to get the right look.

## Referenced Command

```
mirv_movie_ffmpeg main options "-c:v libx264 -pix_fmt yuv420p -preset veryfast -crf 6 {QUOTE}{AFX_STREAM_PATH}\\video.mp4{QUOTE}"
```

**Comment by dtugend** [comment]
I used latest HLAE version and only these settings:

```
mirv_movie_ffmpeg all enabled 1
mirv_movie_ffmpeg main options "-c:v libx264 -pix_fmt yuv420p -preset veryfast -crf 6 {QUOTE}{AFX_STREAM_PATH}\\video.mp4{QUOTE}"
```

And it's fine in https://www.videolan.org VLC.
Please make sure that it's not a limitation of your video editor, because with the default settings that HLAE prepends, it already does actually flip it: https://github.com/advancedfx/advancedfx/blob/602d92471f213c1a3c2d93add9ac7db74a8f82a5/AfxHookGoldSrc/filming.cpp#L123

Edit: also do a raw bmp output for compraison.

Edit2: Provide output of __mirv_info please.

**Comment by dtugend** [comment]
Closing for now due to lacking feeback.
